version: "2"

plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json

exclude_patterns:
- "**/*.gen.ts"
- "**/*.spec.ts"
- "**/*.d.ts"
- "**/node_modules/"
- "dist/"
- "coverage/"