env:
  global:
    - CC_TEST_REPORTER_ID=0f300968304afe777821610f06a73982d55ba2dd4a6c474e63bd984b94b28c57

language: node_js
node_js:
- "8.9"

notifications:
  email:
    recipients:
      - alfonsocfilho@gmail.com
    on_success: never
    on_failure: change

before_install: yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn ci

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload