env:
  global:
    - CC_TEST_REPORTER_ID=a335a3f10bf44ef517759a291efad573ad34f71a6e5fe983ef7e1ca7b58012aa

language: node_js
node_js:
- "8.9"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn ci

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT